import {pages,ui,slugs,labels} from './pages-content.js';
import assets from './page-assets.json' with {type:'json'};
export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const contactText={
 en:{send:'Send message',sending:'Sending…',note:'Your message will be saved securely and forwarded to contact@wonderlang.net. We use your details to answer your request.',success:'Your message has been received. We’ll reply by email. Reference: ',error:'Your message could not be confirmed. Please try again or email contact@wonderlang.net.',rate:'Too many attempts. Please wait before trying again, or email contact@wonderlang.net.',topic:'Topic',topics:['General question','Order or account','Technical issue','Classroom or press'],required:'Please complete the required fields.'},
 fr:{send:'Envoyer le message',sending:'Envoi en cours…',note:'Votre message sera enregistré de manière sécurisée et transmis à contact@wonderlang.net. Vos coordonnées servent à répondre à votre demande.',success:'Votre message a bien été reçu. Nous vous répondrons par e-mail. Référence : ',error:'La réception de votre message n’a pas pu être confirmée. Réessayez ou écrivez à contact@wonderlang.net.',rate:'Trop de tentatives. Veuillez patienter avant de réessayer, ou écrivez à contact@wonderlang.net.',topic:'Sujet',topics:['Question générale','Commande ou compte','Problème technique','École ou presse'],required:'Veuillez remplir les champs obligatoires.'},
 es:{send:'Enviar mensaje',sending:'Enviando…',note:'Tu mensaje se guardará de forma segura y se enviará a contact@wonderlang.net. Usamos tus datos para responder a tu solicitud.',success:'Hemos recibido tu mensaje. Te responderemos por correo. Referencia: ',error:'No se ha podido confirmar la recepción del mensaje. Inténtalo de nuevo o escribe a contact@wonderlang.net.',rate:'Demasiados intentos. Espera antes de volver a intentarlo o escribe a contact@wonderlang.net.',topic:'Tema',topics:['Consulta general','Pedido o cuenta','Problema técnico','Aula o prensa'],required:'Completa los campos obligatorios.'}
};
export function pageLink(slug,lang){return '/testsite/'+(slug?slug+'/':'')+'?lang='+lang}
const link=(url,text,cls='')=>`<a class="${cls}" href="${escape(url)}">${escape(text)}</a>`;
function picture(a,lang,index,alt){return `<a class="screenshot" href="/testsite/page-assets/${a.file}" target="_blank" rel="noopener" aria-label="${escape(ui[lang].media)} ${index+1}"><img src="/testsite/page-assets/${a.file}" width="${a.width}" height="${a.height}" loading="lazy" alt="${escape(alt||ui[lang].shot)} ${alt?'':index+1}"></a>`}
export function renderPage(slug,lang){
 const t=pages[slug][lang],u=ui[lang],c=contactText[lang],legal=['terms-and-conditions','privacy-policy'].includes(slug);
 const aboutAlts={en:['WonderLang illustration','Kickstarter','RPG Maker MZ','Character concept art','WonderLang logo'],fr:['Illustration de WonderLang','Kickstarter','RPG Maker MZ','Recherches graphiques des personnages','Logo de WonderLang'],es:['Ilustración de WonderLang','Kickstarter','RPG Maker MZ','Diseños de personajes','Logotipo de WonderLang']};
 const aboutArt=i=>slug==='crafting-the-game'?([0,1,2,4].includes(i)?(i===2?[2,3]:[i]).map(j=>`<div class="about-art about-art-${j}">${picture(assets.about[j],lang,j,aboutAlts[lang][j])}</div>`).join(''):''):'';
 const sections=t.sections.map(([heading,...paragraphs],i)=>`<section class="article-section" id="section-${i}"><span class="section-index" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><h2>${escape(heading)}</h2>${paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}${slug==='features'&&assets.features[i]?picture(assets.features[i],lang,i):''}${aboutArt(i)}</section>`).join('');
 const form=slug==='contacts'?`<section class="contact-card"><h2>${escape(u.contact)}</h2><p><a href="mailto:contact@wonderlang.net">contact@wonderlang.net</a></p><form id="contact-form" method="post" action="/.netlify/functions/contact"><div class="contact-fields"><label>${escape(u.name)}<input name="name" autocomplete="name" required maxlength="120"></label><label>${escape(u.address)}<input name="email" autocomplete="email" type="email" required maxlength="254"></label></div><label>${escape(c.topic)}<select name="topic">${c.topics.map((x,i)=>`<option value="${['general','order','technical','education_press'][i]}">${escape(x)}</option>`).join('')}</select></label><label>${escape(u.message)}<textarea name="message" rows="7" required minlength="10" maxlength="8000"></textarea></label><div class="contact-trap" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="small">${escape(c.note)} ${link(pageLink('privacy-policy',lang),labels[lang][6])}</p><button class="button primary" type="submit">${escape(c.send)}</button><p id="contact-status" role="status" aria-live="polite"></p></form></section>`:'';
 const media=slug==='media'?`<div class="media-grid">${assets.media.map((a,i)=>picture(a,lang,i)).join('')}</div><div class="video-list">${t.videos.map((v,i)=>`<article><span class="play-icon" aria-hidden="true">▶</span><div><h2>${escape(v)}</h2>${i===3?`<p>${escape(t.archive)}</p>`:''}${link('https://www.youtube.com/watch?v='+['HKizb4Y6J5E','Jm2HiHMG7Pg','F9zVTEGX2Ss','PHzIEWdGbzg'][i],u.watch)}</div></article>`).join('')}</div>`:'';
 return `<a class="skip" href="#main">${escape(u.skip)}</a><header class="site-header"><a class="brand" href="${pageLink('',lang)}"><img src="/testsite/assets/logo.webp" width="145" height="68" alt="WonderLang"></a><nav aria-label="${escape(u.explore)}">${link(pageLink('',lang),u.home)}${link(pageLink('',lang)+'#pricing',u.shop)}${link(pageLink('',lang)+'#funding',u.fund)}</nav><div class="header-tools">${link('/account/?lang='+lang,u.account)}<label class="sr-only" for="page-language">${escape(u.language)}</label><select id="page-language"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="fr" ${lang==='fr'?'selected':''}>Français</option><option value="es" ${lang==='es'?'selected':''}>Español</option></select></div></header><main id="main"><div class="page-hero ${legal?'legal-hero':''}"><div><p class="eyebrow">WONDERLANG / ${escape(labels[lang][slugs.indexOf(slug)])}</p><h1>${escape(t.title)}</h1><p class="page-intro">${escape(t.intro)}</p>${slug==='contacts'?link('#contact-form',u.contact,'button primary'):''}${legal?`<p class="small">${escape(slug==='terms-and-conditions'?u.legalDate:u.updated)}</p>`:''}</div>${legal?'':`<img src="/testsite/assets/${slug==='crafting-the-game'?'jonathan.webp':slug==='study-tips'?'forest.webp':'snow.webp'}" alt="${slug==='crafting-the-game'?'Jonathan':''}" width="600" height="400">`}</div><div class="page-layout ${slug==='media'?'media-layout':''}">${t.sections.length?`<aside class="page-toc"><strong>${escape(u.contents)}</strong>${t.sections.map(([h],i)=>link('#section-'+i,h)).join('')}${link('#top',u.back)}</aside>`:''}<div class="page-article">${sections}${slug==='features'?`<div class="feature-extra">${assets.features.slice(5).map((a,i)=>picture(a,lang,i+5)).join('')}${link(pageLink('study-tips',lang),labels[lang][1],'button outline')}</div>`:''}${slug==='crafting-the-game'?``:''}${form}${media}${slug==='privacy-policy'?`<button class="button outline" id="page-privacy">${escape(u.privacy)}</button>`:''}${slug==='terms-and-conditions'&&lang!=='en'?`<p class="small">${escape(u.legalNote)}</p>`:''}</div></div>${legal?'':`<section class="page-cta"><h2>${escape(u.cta)}</h2><p>${escape(u.ctaCopy)}</p><div class="actions">${link(pageLink('',lang)+'#demo',u.demo,'button primary')}${link(pageLink('',lang)+'#pricing',u.shop,'button outline')}</div></section>`}</main><footer><a class="brand" href="${pageLink('',lang)}"><img src="/testsite/assets/logo.webp" width="145" height="68" alt="WonderLang" loading="lazy"></a><p>${escape(u.footer)}</p><div>${link('mailto:contact@wonderlang.net',u.contact)}${link('https://discord.gg/WvzWBqhtXn','Discord')}</div><small>WonderLang · ${lang==='es'?'París, Francia':'Paris, France'}</small></footer>`;
}
