// Manually authored sign-in page and email-confirmation dialog translations.
// Keep each row in the same order as the English source row.
export const loginText = {
  en: ["PC / MAC SIGN-IN", "Continue in WonderLang.", "or use email", "Email me a sign-in link", "Sign in with a password", "Password", "Sign in", "Loading account…", "Opening secure sign-in…", "Check your email for the secure sign-in link.", "SECURE SIGN-IN", "Confirm your email", "Cancel", "Continue", "This sign-in link was opened on a different browser or device. Enter the same email address that received the link.", "Sign in first.", "The sign-in popup is unavailable. Continuing securely in this browser…"],
  fr: ["CONNEXION PC / MAC", "Continuez dans WonderLang.", "ou utilisez votre e-mail", "Recevoir un lien de connexion", "Se connecter avec un mot de passe", "Mot de passe", "Se connecter", "Chargement du compte…", "Ouverture de la connexion sécurisée…", "Consultez vos e-mails pour trouver le lien de connexion sécurisé.", "CONNEXION SÉCURISÉE", "Confirmez votre adresse e-mail", "Annuler", "Continuer", "Ce lien de connexion a été ouvert dans un autre navigateur ou sur un autre appareil. Saisissez l’adresse e-mail qui a reçu le lien.", "Connectez-vous d’abord.", "La fenêtre de connexion est indisponible. La connexion sécurisée se poursuit dans ce navigateur…"],
  de: ["ANMELDUNG FÜR PC / MAC", "Weiter in WonderLang.", "oder per E-Mail", "Anmeldelink per E-Mail erhalten", "Mit Passwort anmelden", "Passwort", "Anmelden", "Konto wird geladen…", "Sichere Anmeldung wird geöffnet…", "Den sicheren Anmeldelink findest du in deinen E-Mails.", "SICHERE ANMELDUNG", "Bestätige deine E-Mail-Adresse", "Abbrechen", "Weiter", "Dieser Anmeldelink wurde in einem anderen Browser oder auf einem anderen Gerät geöffnet. Gib die E-Mail-Adresse ein, an die der Link gesendet wurde.", "Melde dich zuerst an.", "Das Anmeldefenster ist nicht verfügbar. Die sichere Anmeldung wird in diesem Browser fortgesetzt…"],
  es: ["ACCESO PARA PC / MAC", "Continúa en WonderLang.", "o usa tu correo electrónico", "Recibir un enlace de acceso", "Iniciar sesión con contraseña", "Contraseña", "Iniciar sesión", "Cargando cuenta…", "Abriendo el acceso seguro…", "Busca el enlace de acceso seguro en tu correo electrónico.", "ACCESO SEGURO", "Confirma tu correo electrónico", "Cancelar", "Continuar", "Este enlace de acceso se ha abierto en otro navegador o dispositivo. Introduce la dirección de correo que recibió el enlace.", "Inicia sesión primero.", "La ventana de acceso no está disponible. El acceso seguro continuará en este navegador…"],
  "es-MX": ["ACCESO PARA PC / MAC", "Continúa en WonderLang.", "o usa tu correo electrónico", "Recibir un enlace de acceso", "Iniciar sesión con contraseña", "Contraseña", "Iniciar sesión", "Cargando cuenta…", "Abriendo el acceso seguro…", "Busca el enlace de acceso seguro en tu correo electrónico.", "ACCESO SEGURO", "Confirma tu correo electrónico", "Cancelar", "Continuar", "Este enlace de acceso se abrió en otro navegador o dispositivo. Ingresa la dirección de correo que recibió el enlace.", "Inicia sesión primero.", "La ventana de acceso no está disponible. El acceso seguro continuará en este navegador…"],
  "pt-BR": ["LOGIN PARA PC / MAC", "Continue no WonderLang.", "ou use seu e-mail", "Receber um link de login", "Entrar com uma senha", "Senha", "Entrar", "Carregando conta…", "Abrindo o login seguro…", "Confira seu e-mail para encontrar o link de login seguro.", "LOGIN SEGURO", "Confirme seu e-mail", "Cancelar", "Continuar", "Este link de login foi aberto em outro navegador ou dispositivo. Digite o endereço de e-mail que recebeu o link.", "Entre na sua conta primeiro.", "A janela de login não está disponível. O login seguro continuará neste navegador…"],
  "pt-PT": ["INÍCIO DE SESSÃO PARA PC / MAC", "Continua no WonderLang.", "ou usa o teu e-mail", "Receber uma ligação de início de sessão", "Iniciar sessão com uma palavra-passe", "Palavra-passe", "Iniciar sessão", "A carregar a conta…", "A abrir o início de sessão seguro…", "Consulta o teu e-mail para encontrares a ligação de início de sessão seguro.", "INÍCIO DE SESSÃO SEGURO", "Confirma o teu e-mail", "Cancelar", "Continuar", "Esta ligação de início de sessão foi aberta noutro navegador ou dispositivo. Introduz o endereço de e-mail que recebeu a ligação.", "Inicia sessão primeiro.", "A janela de início de sessão não está disponível. O início de sessão seguro continuará neste navegador…"],
  it: ["ACCESSO PER PC / MAC", "Continua in WonderLang.", "oppure usa l’e-mail", "Ricevi un link di accesso", "Accedi con una password", "Password", "Accedi", "Caricamento dell’account…", "Apertura dell’accesso sicuro…", "Controlla la tua e-mail per trovare il link di accesso sicuro.", "ACCESSO SICURO", "Conferma il tuo indirizzo e-mail", "Annulla", "Continua", "Questo link di accesso è stato aperto in un altro browser o su un altro dispositivo. Inserisci l’indirizzo e-mail che ha ricevuto il link.", "Accedi prima di continuare.", "La finestra di accesso non è disponibile. L’accesso sicuro continuerà in questo browser…"],
  nl: ["INLOGGEN VOOR PC / MAC", "Ga verder in WonderLang.", "of gebruik e-mail", "Ontvang een inloglink per e-mail", "Inloggen met een wachtwoord", "Wachtwoord", "Inloggen", "Account laden…", "Beveiligd inloggen openen…", "Controleer je e-mail voor de beveiligde inloglink.", "BEVEILIGD INLOGGEN", "Bevestig je e-mailadres", "Annuleren", "Doorgaan", "Deze inloglink is in een andere browser of op een ander apparaat geopend. Vul het e-mailadres in waarop je de link hebt ontvangen.", "Log eerst in.", "Het inlogvenster is niet beschikbaar. Beveiligd inloggen gaat verder in deze browser…"],
  sv: ["INLOGGNING FÖR PC / MAC", "Fortsätt i WonderLang.", "eller använd e-post", "Få en inloggningslänk via e-post", "Logga in med lösenord", "Lösenord", "Logga in", "Laddar konto…", "Öppnar säker inloggning…", "Kontrollera din e-post för den säkra inloggningslänken.", "SÄKER INLOGGNING", "Bekräfta din e-postadress", "Avbryt", "Fortsätt", "Den här inloggningslänken öppnades i en annan webbläsare eller på en annan enhet. Ange e-postadressen som tog emot länken.", "Logga in först.", "Inloggningsfönstret är inte tillgängligt. Säker inloggning fortsätter i den här webbläsaren…"],
  pl: ["LOGOWANIE NA PC / MAC", "Kontynuuj w WonderLang.", "lub użyj adresu e-mail", "Otrzymaj link do logowania", "Zaloguj się hasłem", "Hasło", "Zaloguj się", "Ładowanie konta…", "Otwieranie bezpiecznego logowania…", "Sprawdź pocztę, aby znaleźć bezpieczny link do logowania.", "BEZPIECZNE LOGOWANIE", "Potwierdź swój adres e-mail", "Anuluj", "Kontynuuj", "Ten link do logowania został otwarty w innej przeglądarce lub na innym urządzeniu. Wpisz adres e-mail, na który wysłano link.", "Najpierw się zaloguj.", "Okno logowania jest niedostępne. Bezpieczne logowanie będzie kontynuowane w tej przeglądarce…"],
  uk: ["ВХІД НА PC / MAC", "Продовжуйте у WonderLang.", "або скористайтеся електронною поштою", "Отримати посилання для входу", "Увійти за допомогою пароля", "Пароль", "Увійти", "Завантаження облікового запису…", "Відкриття безпечного входу…", "Знайдіть у своїй пошті безпечне посилання для входу.", "БЕЗПЕЧНИЙ ВХІД", "Підтвердьте свою електронну адресу", "Скасувати", "Продовжити", "Це посилання для входу відкрито в іншому браузері або на іншому пристрої. Введіть електронну адресу, на яку надійшло посилання.", "Спочатку увійдіть.", "Вікно входу недоступне. Безпечний вхід продовжиться в цьому браузері…"],
  ru: ["ВХОД НА PC / MAC", "Продолжите в WonderLang.", "или используйте электронную почту", "Получить ссылку для входа", "Войти с паролем", "Пароль", "Войти", "Загрузка учётной записи…", "Открытие безопасного входа…", "Найдите в своей почте безопасную ссылку для входа.", "БЕЗОПАСНЫЙ ВХОД", "Подтвердите свой адрес электронной почты", "Отмена", "Продолжить", "Эта ссылка для входа открыта в другом браузере или на другом устройстве. Введите адрес электронной почты, на который пришла ссылка.", "Сначала войдите.", "Окно входа недоступно. Безопасный вход продолжится в этом браузере…"],
  id: ["MASUK UNTUK PC / MAC", "Lanjutkan di WonderLang.", "atau gunakan email", "Kirim tautan masuk ke email saya", "Masuk dengan kata sandi", "Kata sandi", "Masuk", "Memuat akun…", "Membuka proses masuk yang aman…", "Periksa email Anda untuk menemukan tautan masuk yang aman.", "MASUK DENGAN AMAN", "Konfirmasikan alamat email Anda", "Batal", "Lanjutkan", "Tautan masuk ini dibuka di browser atau perangkat lain. Masukkan alamat email yang menerima tautan tersebut.", "Masuk terlebih dahulu.", "Jendela masuk tidak tersedia. Proses masuk yang aman akan dilanjutkan di browser ini…"],
  ko: ["PC / MAC 로그인", "WonderLang에서 계속하세요.", "또는 이메일 사용", "이메일로 로그인 링크 받기", "비밀번호로 로그인", "비밀번호", "로그인", "계정 불러오는 중…", "보안 로그인 여는 중…", "이메일에서 보안 로그인 링크를 확인하세요.", "보안 로그인", "이메일 주소 확인", "취소", "계속", "이 로그인 링크가 다른 브라우저 또는 기기에서 열렸습니다. 링크를 받은 이메일 주소를 입력하세요.", "먼저 로그인하세요.", "로그인 창을 사용할 수 없습니다. 이 브라우저에서 보안 로그인을 계속합니다…"],
  ja: ["PC / MAC ログイン", "WonderLangで続けましょう。", "またはメールを使用", "ログインリンクをメールで受け取る", "パスワードでログイン", "パスワード", "ログイン", "アカウントを読み込み中…", "安全なログインを開いています…", "メールに届いた安全なログインリンクを確認してください。", "安全なログイン", "メールアドレスの確認", "キャンセル", "続ける", "このログインリンクは別のブラウザーまたはデバイスで開かれました。リンクを受け取ったメールアドレスを入力してください。", "先にログインしてください。", "ログインウィンドウを利用できません。このブラウザーで安全なログインを続けます…"],
  "zh-CN": ["PC / MAC 登录", "在 WonderLang 中继续。", "或使用电子邮件", "通过邮件接收登录链接", "使用密码登录", "密码", "登录", "正在加载账户…", "正在打开安全登录…", "请查看邮件中的安全登录链接。", "安全登录", "确认您的邮箱地址", "取消", "继续", "此登录链接已在其他浏览器或设备上打开。请输入收到该链接的邮箱地址。", "请先登录。", "登录窗口不可用。将在此浏览器中继续安全登录…"],
  "zh-TW": ["PC / MAC 登入", "在 WonderLang 中繼續。", "或使用電子郵件", "透過郵件接收登入連結", "使用密碼登入", "密碼", "登入", "正在載入帳戶…", "正在開啟安全登入…", "請查看郵件中的安全登入連結。", "安全登入", "確認您的電子郵件地址", "取消", "繼續", "此登入連結已在其他瀏覽器或裝置上開啟。請輸入收到該連結的電子郵件地址。", "請先登入。", "登入視窗無法使用。將在此瀏覽器中繼續安全登入…"],
  ar: ["تسجيل الدخول على PC / MAC", "تابع في WonderLang.", "أو استخدم البريد الإلكتروني", "أرسل إليّ رابط تسجيل الدخول", "تسجيل الدخول بكلمة مرور", "كلمة المرور", "تسجيل الدخول", "جارٍ تحميل الحساب…", "جارٍ فتح تسجيل الدخول الآمن…", "تحقّق من بريدك الإلكتروني للعثور على رابط تسجيل الدخول الآمن.", "تسجيل الدخول الآمن", "أكّد عنوان بريدك الإلكتروني", "إلغاء", "متابعة", "فُتح رابط تسجيل الدخول هذا في متصفح آخر أو على جهاز آخر. أدخل عنوان البريد الإلكتروني الذي استلم الرابط.", "سجّل الدخول أولًا.", "نافذة تسجيل الدخول غير متاحة. ستستمر عملية تسجيل الدخول الآمن في هذا المتصفح…"],
  hy: ["ՄՈՒՏՔ PC / MAC-ՈՒՄ", "Շարունակեք WonderLang-ում։", "կամ օգտագործեք էլեկտրոնային փոստը", "Ստանալ մուտքի հղումն էլեկտրոնային փոստով", "Մուտք գործել գաղտնաբառով", "Գաղտնաբառ", "Մուտք գործել", "Հաշիվը բեռնվում է…", "Բացվում է անվտանգ մուտքի էջը…", "Ստուգեք ձեր էլեկտրոնային փոստը՝ անվտանգ մուտքի հղումը գտնելու համար։", "ԱՆՎՏԱՆԳ ՄՈՒՏՔ", "Հաստատեք ձեր էլեկտրոնային փոստի հասցեն", "Չեղարկել", "Շարունակել", "Մուտքի այս հղումը բացվել է այլ դիտարկիչում կամ այլ սարքում։ Մուտքագրեք այն էլեկտրոնային փոստի հասցեն, որով ստացել եք հղումը։", "Նախ մուտք գործեք։", "Մուտքի պատուհանն անհասանելի է։ Անվտանգ մուտքը կշարունակվի այս դիտարկիչում…"]
};

// Signed-out banners for the regular account page and PC/Mac approval flow.
const loginStatusText = {
  en: ["Sign in to sync purchases and cloud saves across platforms.", "Sign in to review the PC/Mac request. No device is approved until you confirm it."],
  fr: ["Connectez-vous pour synchroniser vos achats et vos sauvegardes cloud entre les plateformes.", "Connectez-vous pour consulter la demande PC/Mac. Aucun appareil ne sera autorisé sans votre confirmation."],
  de: ["Melde dich an, um Käufe und Cloud-Spielstände plattformübergreifend zu synchronisieren.", "Melde dich an, um die PC/Mac-Anfrage zu prüfen. Kein Gerät wird ohne deine Bestätigung autorisiert."],
  es: ["Inicia sesión para sincronizar tus compras y partidas en la nube entre plataformas.", "Inicia sesión para revisar la solicitud de PC/Mac. No se autorizará ningún dispositivo sin tu confirmación."],
  "es-MX": ["Inicia sesión para sincronizar tus compras y partidas en la nube entre plataformas.", "Inicia sesión para revisar la solicitud de PC/Mac. No se autorizará ningún dispositivo sin tu confirmación."],
  "pt-BR": ["Entre para sincronizar suas compras e jogos salvos na nuvem entre plataformas.", "Entre para revisar a solicitação do PC/Mac. Nenhum dispositivo será autorizado sem sua confirmação."],
  "pt-PT": ["Inicia sessão para sincronizar as tuas compras e os jogos guardados na nuvem entre plataformas.", "Inicia sessão para rever o pedido do PC/Mac. Nenhum dispositivo será autorizado sem a tua confirmação."],
  it: ["Accedi per sincronizzare acquisti e salvataggi cloud tra piattaforme.", "Accedi per esaminare la richiesta PC/Mac. Nessun dispositivo sarà autorizzato senza la tua conferma."],
  nl: ["Log in om aankopen en opgeslagen spellen in de cloud tussen platforms te synchroniseren.", "Log in om het PC/Mac-verzoek te bekijken. Geen enkel apparaat wordt zonder jouw bevestiging geautoriseerd."],
  sv: ["Logga in för att synkronisera köp och molnsparfiler mellan plattformar.", "Logga in för att granska PC/Mac-förfrågan. Ingen enhet godkänns utan din bekräftelse."],
  pl: ["Zaloguj się, aby synchronizować zakupy i zapisy w chmurze między platformami.", "Zaloguj się, aby sprawdzić żądanie z PC/Mac. Żadne urządzenie nie zostanie autoryzowane bez Twojego potwierdzenia."],
  uk: ["Увійдіть, щоб синхронізувати покупки та хмарні збереження між платформами.", "Увійдіть, щоб переглянути запит із PC/Mac. Жоден пристрій не буде авторизовано без вашого підтвердження."],
  ru: ["Войдите, чтобы синхронизировать покупки и облачные сохранения между платформами.", "Войдите, чтобы просмотреть запрос с PC/Mac. Ни одно устройство не будет авторизовано без вашего подтверждения."],
  id: ["Masuk untuk menyinkronkan pembelian dan data permainan di cloud antarplatform.", "Masuk untuk meninjau permintaan PC/Mac. Tidak ada perangkat yang disetujui tanpa konfirmasi Anda."],
  ko: ["플랫폼 간 구매 내역과 클라우드 저장 데이터를 동기화하려면 로그인하세요.", "PC/Mac 요청을 검토하려면 로그인하세요. 확인하기 전에는 어떤 기기도 승인되지 않습니다."],
  ja: ["購入情報とクラウドセーブをプラットフォーム間で同期するには、ログインしてください。", "PC/Macからのリクエストを確認するには、ログインしてください。確認するまで、デバイスは承認されません。"],
  "zh-CN": ["登录以跨平台同步购买记录和云存档。", "登录以查看 PC/Mac 请求。未经您的确认，任何设备都不会获得授权。"],
  "zh-TW": ["登入以跨平台同步購買記錄和雲端存檔。", "登入以查看 PC/Mac 請求。未經您的確認，任何裝置都不會獲得授權。"],
  ar: ["سجّل الدخول لمزامنة المشتريات وملفات الحفظ السحابي عبر المنصات.", "سجّل الدخول لمراجعة طلب PC/Mac. لن يُعتمد أي جهاز دون تأكيدك."],
  hy: ["Մուտք գործեք՝ գնումներն ու ամպային պահպանումները տարբեր հարթակների միջև համաժամեցնելու համար։", "Մուտք գործեք՝ PC/Mac-ի հարցումը դիտելու համար։ Ոչ մի սարք չի հաստատվի առանց ձեր հաստատման։"]
};
for (const [locale, values] of Object.entries(loginStatusText)) loginText[locale].push(...values);
