const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderContacts(data){return `<section class="panel contact-inbox"><h2>Contact inbox</h2><p>Website messages are saved here and forwarded to contact@wonderlang.net. “Sent” means the mail relay accepted the email.</p><label>Search this page <input id="contact-search" type="search" placeholder="Name, email or message"></label><label>Status <select id="contact-filter"><option value="">All</option><option value="new">New</option><option value="read">Read</option><option value="resolved">Resolved</option></select></label><div id="contact-results">${contactRows(data.messages||[])}</div>${data.nextCursor?`<button class="button secondary" id="contact-more" data-cursor="${esc(data.nextCursor)}">Load older messages</button>`:''}<p id="contact-empty" hidden>No matching messages.</p></section>`}
function contactRows(rows){return rows.length?rows.map(m=>`<details class="panel contact-inbox-row" data-id="${esc(m.id)}" data-status="${esc(m.status)}"><summary><strong>${esc(m.name)}</strong> · ${esc(m.email)} · ${esc(m.createdAt)} · ${esc(m.status)} · Email: ${esc(m.emailState)}</summary><p>${esc(m.topic)} · ${esc(m.locale)} · ${esc(m.id)}</p><pre class="contact-inbox-message">${esc(m.message)}</pre>${m.lastError?`<p class="error">${esc(m.lastError)}</p>`:''}<a class="button secondary" href="mailto:${esc(m.email)}?subject=${encodeURIComponent('Re: WonderLang — '+m.topic)}">Reply by email</a> <button class="button secondary" data-contact-status="read" data-id="${esc(m.id)}">Mark read</button> <button class="button secondary" data-contact-status="resolved" data-id="${esc(m.id)}">Mark resolved</button> ${m.emailState==='failed'?`<button class="button secondary" data-contact-retry="${esc(m.id)}">Retry email forwarding</button>`:''}</details>`).join(''):'<p>No contact messages yet.</p>'}
export function bindContacts({api,toast,reload}){
 const filter=()=>{const q=document.getElementById('contact-search').value.toLowerCase(),status=document.getElementById('contact-filter').value;let count=0;document.querySelectorAll('.contact-inbox-row').forEach(n=>{n.hidden=!!((status&&n.dataset.status!==status)||!n.textContent.toLowerCase().includes(q));if(!n.hidden)count++});document.getElementById('contact-empty').hidden=count>0};
 document.getElementById('contact-search').addEventListener('input',filter);document.getElementById('contact-filter').addEventListener('change',filter);
 document.getElementById('contact-results').addEventListener('click',async e=>{const b=e.target.closest('[data-contact-status],[data-contact-retry]');if(!b)return;b.disabled=true;try{await api('/admin-api/v1/contacts/'+(b.dataset.id||b.dataset.contactRetry),{method:'POST',body:b.dataset.contactRetry?{retryEmail:true}:{status:b.dataset.contactStatus}});await reload()}catch(error){toast(error.message,true);b.disabled=false}});
 document.getElementById('contact-more')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{const data=await api('/admin-api/v1/contacts?cursor='+encodeURIComponent(b.dataset.cursor));document.getElementById('contact-results').insertAdjacentHTML('beforeend',contactRows(data.messages));if(data.nextCursor)b.dataset.cursor=data.nextCursor;else b.remove();filter()}catch(error){toast(error.message,true)}finally{b.disabled=false}});
}
